-- Auto-generated reading seed for grammar and vocabulary
-- Safe to re-run.

update public.grammar set reading = '～とき', example_reading = 'あめがふっているとき、かさをもってください。' where id = 'N4_001';
update public.grammar set reading = '～ときに', example_reading = 'かれがきたときに、わたしはねていました。' where id = 'N4_002';
update public.grammar set reading = '～ながら', example_reading = 'うたいながら、おどります。' where id = 'N4_003';
update public.grammar set reading = '～ながらも', example_reading = 'おかねがないながらも、なんとかいきています。' where id = 'N4_004';
update public.grammar set reading = '～ば', example_reading = 'べんきょうすれば、しけんにごうかくできます。' where id = 'N4_005';
update public.grammar set reading = '～たら', example_reading = 'あした、あめがふったら、きません。' where id = 'N4_006';
update public.grammar set reading = '～なら', example_reading = 'もしじかんがあるなら、てつだってください。' where id = 'N4_007';
update public.grammar set reading = '～ても', example_reading = 'どんなにどりょくしても、しっぱいすることがあります。' where id = 'N4_008';
update public.grammar set reading = '～たとしても', example_reading = 'かれがきたとしても、あわない。' where id = 'N4_009';
update public.grammar set reading = '～だろう', example_reading = 'あした、あめがふるだろう。' where id = 'N4_010';
update public.grammar set reading = '～でしょう', example_reading = 'あしたははれるでしょう。' where id = 'N4_011';
update public.grammar set reading = '～かもしれない', example_reading = 'かれはあしたくるかもしれません。' where id = 'N4_012';
update public.grammar set reading = '～ようだ', example_reading = 'かれはつかれているようです。' where id = 'N4_013';
update public.grammar set reading = '～ようです', example_reading = 'てんきがよくなるようです。' where id = 'N4_014';
update public.grammar set reading = '～そうだ', example_reading = 'かれはにっぽんにいくそうです。' where id = 'N4_015';
update public.grammar set reading = '～られる', example_reading = 'わたしはにほんごをよむことができます。' where id = 'N4_016';
update public.grammar set reading = '～させる', example_reading = 'せんせいはがくせいにしゅくだいをさせた。' where id = 'N4_017';
update public.grammar set reading = '～させられる', example_reading = 'わたしはまいにち、つらいしごとをさせられています。' where id = 'N4_018';
update public.grammar set reading = '～られる', example_reading = 'ぶんしょうはちゅういぶかくよまれた。' where id = 'N4_019';
update public.grammar set reading = '～るべき', example_reading = 'べんきょうすべきです。' where id = 'N4_020';
update public.grammar set reading = '～たほうがいい', example_reading = 'びょうきなら、いしゃにいったほうがいいです。' where id = 'N4_021';
update public.grammar set reading = '～つつ', example_reading = 'なきつつ、まえにすすみます。' where id = 'N4_022';
update public.grammar set reading = '～てしまう', example_reading = 'しゅくだいをわすれてしまった。' where id = 'N4_023';
update public.grammar set reading = '～ておく', example_reading = 'あしたのために、こんやははやくねておきます。' where id = 'N4_024';
update public.grammar set reading = '～ていただく', example_reading = 'てつだっていただけますか。' where id = 'N4_025';
update public.grammar set reading = '～てくれる', example_reading = 'ともだちはわたしをてつだってくれた。' where id = 'N4_026';
update public.grammar set reading = '～てくださる', example_reading = 'せんせいがおしえてくださいました。' where id = 'N4_027';
update public.grammar set reading = '～てあげる', example_reading = 'わたしはともだちをてつだってあげた。' where id = 'N4_028';
update public.grammar set reading = '～てもらう', example_reading = 'せんせいにしゅくだいをてつだってもらった。' where id = 'N4_029';
update public.grammar set reading = '～ために', example_reading = 'ごうかくするために、まいにちべんきょうします。' where id = 'N4_030';
update public.grammar set reading = '～ために', example_reading = 'あめがふったため、しあいがちゅうしになった。' where id = 'N4_031';
update public.grammar set reading = '～ように', example_reading = 'よくみえるように、めがねをかけます。' where id = 'N4_032';
update public.grammar set reading = '～という', example_reading = 'たなかというがくせいがきました。' where id = 'N4_033';
update public.grammar set reading = '～ではない', example_reading = 'かれはがくせいではありません。' where id = 'N4_034';
update public.grammar set reading = '～じゃない', example_reading = 'あれはほんじゃない。' where id = 'N4_035';
update public.grammar set reading = '～ではなく', example_reading = 'こーひーではなく、こうちゃがすきです。' where id = 'N4_036';
update public.grammar set reading = '～てはいけない', example_reading = 'ここでしゃしんをとってはいけません。' where id = 'N4_037';
update public.grammar set reading = '～ないでください', example_reading = 'ここでさわがないでください。' where id = 'N4_038';
update public.grammar set reading = '～のに', example_reading = 'がんばったのに、しっぱいした。' where id = 'N4_039';
update public.grammar set reading = '～べき', example_reading = 'がくせいはべんきょうすべきだ。' where id = 'N4_040';
update public.grammar set reading = '～みたい', example_reading = 'かれはつかれているみたいです。' where id = 'N4_041';
update public.grammar set reading = '～らしい', example_reading = 'かれはおとこらしいふるまいをしている。' where id = 'N4_042';
update public.grammar set reading = '～いく', example_reading = 'あめがふりつづきます。' where id = 'N4_043';
update public.grammar set reading = '～くる', example_reading = 'はるがきました。' where id = 'N4_044';
update public.grammar set reading = '～ことにする', example_reading = 'まいにち、じょぎんぐすることにしました。' where id = 'N4_045';
update public.grammar set reading = '～ことになった', example_reading = 'らいねん、にっぽんにいくことになりました。' where id = 'N4_046';
update public.grammar set reading = '～ことがある', example_reading = 'ときどき、まちがえることがあります。' where id = 'N4_047';
update public.grammar set reading = '～たことがある', example_reading = 'わたしはにっぽんにいったことがあります。' where id = 'N4_048';
update public.grammar set reading = '～ことができる', example_reading = 'わたしはおよぐことができます。' where id = 'N4_049';
update public.grammar set reading = '～ある', example_reading = 'てーぶるのうえにはながかざってあります。' where id = 'N4_050';
update public.grammar set reading = '～ということ', example_reading = 'かれはこないということですね。' where id = 'N4_051';
update public.grammar set reading = '～にしては', example_reading = 'かれはがくせいにしては、よくべんきょうしています。' where id = 'N4_052';
update public.grammar set reading = '～としたら', example_reading = 'かれがきたとしたら、なにといいますか。' where id = 'N4_053';
update public.grammar set reading = '～にしてみると', example_reading = 'がいこくじんにしてみると、にほんごはむずかしいです。' where id = 'N4_054';
update public.grammar set reading = '～あたり', example_reading = 'いちにんあたり、せんえんかかります。' where id = 'N4_055';
update public.grammar set reading = '～ごと', example_reading = 'くにごとにぶんかがちがいます。' where id = 'N4_056';
update public.grammar set reading = '～ようとしている', example_reading = 'かれはいえにかえろうとしています。' where id = 'N4_057';
update public.grammar set reading = '～ように', example_reading = 'じょうずになるように、まいにちれんしゅうしています。' where id = 'N4_058';
update public.grammar set reading = '～ほか（ない）', example_reading = 'やるほかない。' where id = 'N4_059';
update public.grammar set reading = '～ものなら', example_reading = 'できるものなら、やってみなさい。' where id = 'N4_060';
update public.grammar set reading = '～です', example_reading = 'わたしはがくせいです。' where id = 'N5_001';
update public.grammar set reading = '～ます', example_reading = 'まいにち、がっこうにいきます。' where id = 'N5_002';
update public.grammar set reading = '～ました', example_reading = 'きのう、ともだちにあいました。' where id = 'N5_003';
update public.grammar set reading = '～ない', example_reading = 'わたしはにくをたべません。' where id = 'N5_004';
update public.grammar set reading = '～ません', example_reading = 'あしたはきません。' where id = 'N5_005';
update public.grammar set reading = '～ている', example_reading = 'いま、わたしはしゅくだいをしています。' where id = 'N5_006';
update public.grammar set reading = '～ています / ～ていません', example_reading = 'かれはこうえんであそんでいます。/ かれはこうえんであそんでいません。' where id = 'N5_007';
update public.grammar set reading = '～ていた', example_reading = 'こどものとき、まいにちこうえんであそんでいました。' where id = 'N5_008';
update public.grammar set reading = '～ました / ～てください', example_reading = 'ここにすわってください。' where id = 'N5_009';
update public.grammar set reading = '～くださいませんか', example_reading = 'てつだってくださいませんか。' where id = 'N5_010';
update public.grammar set reading = '～ましょう', example_reading = 'いっしょにえいがをみましょう。' where id = 'N5_011';
update public.grammar set reading = '～ましょうか', example_reading = 'にもつをもちましょうか。' where id = 'N5_012';
update public.grammar set reading = '～ません', example_reading = 'わたしはあしたきません。' where id = 'N5_013';
update public.grammar set reading = '～てください', example_reading = 'みずをのんでください。' where id = 'N5_014';
update public.grammar set reading = '～ました', example_reading = 'あさごはんをたべました。' where id = 'N5_015';
update public.grammar set reading = '～も', example_reading = 'わたしもがくせいです。' where id = 'N5_016';
update public.grammar set reading = '～が', example_reading = 'わたしががくせいです。/ あめがふっています。/ わたしはせがたかいです。' where id = 'N5_017';
update public.grammar set reading = '～を', example_reading = 'ほんをよみます。' where id = 'N5_018';
update public.grammar set reading = '～に', example_reading = 'がっこうにいきます。/ てーぶるのうえにほんがあります。' where id = 'N5_019';
update public.grammar set reading = '～へ', example_reading = 'いえへかえります。' where id = 'N5_020';
update public.grammar set reading = '～で', example_reading = 'としょかんでべんきょうします。/ ぺんでかきます。/ びょうきでやすみます。' where id = 'N5_021';
update public.grammar set reading = '～から', example_reading = 'げつようびからきんようびまでのまにしごとをします。/ あめがふっているから、いえにいます。' where id = 'N5_022';
update public.grammar set reading = '～まで', example_reading = '5じまではたらきます。/ えきまであるきます。' where id = 'N5_023';
update public.grammar set reading = '～は', example_reading = 'わたしはがくせいです。/ きょうはさむいです。' where id = 'N5_024';
update public.grammar set reading = '～の', example_reading = 'わたしのほん (my book); うつくしいじょせいのこえ (the voice of a beautiful woman)' where id = 'N5_025';
update public.grammar set reading = '～や', example_reading = 'りんごやみかんをたべます。' where id = 'N5_026';
update public.grammar set reading = '～と', example_reading = 'ともだちとえいがをみます。/ あめがふると、ひとびとがかさをもちます。' where id = 'N5_027';
update public.grammar set reading = '～て', example_reading = 'はしってあそびます。(run and play) / びょうきで、しごとをやすみます。(because sick, I take work leave)' where id = 'N5_028';
update public.grammar set reading = '～た', example_reading = 'きのう、がっこうにいった。' where id = 'N5_029';
update public.grammar set reading = '～だ', example_reading = 'おれはがくせいだ。' where id = 'N5_030';
update public.grammar set reading = '～ある', example_reading = 'わたしはねこをかっています。/ てーぶるのうえにほんがあります。' where id = 'N5_031';
update public.grammar set reading = '～いる', example_reading = 'きょうしつにせんせいがいます。' where id = 'N5_032';
update public.grammar set reading = '～られる', example_reading = 'わたしはにほんごがはなせます。' where id = 'N5_033';
update public.grammar set reading = '～える', example_reading = 'わたしはおよぐことができます。/ みずをのめる。' where id = 'N5_034';
update public.grammar set reading = '～ことができる', example_reading = 'わたしはにほんごをはなすことができます。' where id = 'N5_035';
update public.grammar set reading = '～ないといけない', example_reading = 'まいにち、しゅくだいをしないといけません。' where id = 'N5_036';
update public.grammar set reading = '～なければならない', example_reading = 'あした、がっこうにいかなければなりません。' where id = 'N5_037';
update public.grammar set reading = '～もしくは', example_reading = 'こーひーもしくはこうちゃをください。' where id = 'N5_038';
update public.grammar set reading = '～ばいい', example_reading = 'まいにち、べんきょうすればいいです。' where id = 'N5_039';
update public.grammar set reading = '～ので', example_reading = 'あめがふっているので、いえにいます。' where id = 'N5_040';
update public.grammar set reading = '～ていない', example_reading = 'いま、わたしはしゅくだいをしていません。' where id = 'N5_041';
update public.grammar set reading = '～られている', example_reading = 'ぶんしょうはちゅういぶかくよまれています。' where id = 'N5_042';
update public.grammar set reading = '～すぎる', example_reading = 'このこーひーはあつすぎます。' where id = 'N5_043';
update public.grammar set reading = '～ず', example_reading = 'なにもいわずにさった。' where id = 'N5_044';
update public.grammar set reading = '～たり', example_reading = 'はしったり、あるいたり、うんどうをしています。' where id = 'N5_045';
update public.grammar set reading = '～てから', example_reading = 'しゅくだいをおわらしてから、そとであそびます。' where id = 'N5_046';
update public.grammar set reading = '～ばかり', example_reading = 'まいにち、げーむばかりしています。' where id = 'N5_047';
update public.grammar set reading = '～たばかり', example_reading = 'かれはけさ、にっぽんについたばかりです。' where id = 'N5_048';
update public.grammar set reading = '～ばいい / ～たらいい', example_reading = 'もっとべんきょうすればいい。/ もっとべんきょうしたらいいのに。' where id = 'N5_049';
update public.grammar set reading = '～だから', example_reading = 'いそがしいから、こられない。' where id = 'N5_050';

update public.vocabulary set example_reading = 'びょういんのいしゃはかんじゃをしんさつする。' where id = '1';
update public.vocabulary set example_reading = 'べんごしはほうりつのせんもんかである。' where id = '2';
update public.vocabulary set example_reading = 'けんちくかはうつくしいたてものをせっけいする。' where id = '3';
update public.vocabulary set example_reading = 'そふとうぇあえんじにあはぷろぐらむをかいはつする。' where id = '4';
update public.vocabulary set example_reading = 'ぐらふぃっくでざいなーはこうこくをさくせいする。' where id = '5';
update public.vocabulary set example_reading = 'だいがくのきょうじゅはがくせいにこうぎをする。' where id = '6';
update public.vocabulary set example_reading = 'けんきゅうしゃはあたらしいぎじゅつをかいはつする。' where id = '7';
update public.vocabulary set example_reading = 'げいじゅつかはそうぞうてきなさくひんをつくる。' where id = '8';
update public.vocabulary set example_reading = 'おんがくかはこんさーとでえんそうする。' where id = '9';
update public.vocabulary set example_reading = 'さっかはしょうせつをしっぴつする。' where id = '10';
update public.vocabulary set example_reading = 'きしゃはにゅーすをしゅざいする。' where id = '11';
update public.vocabulary set example_reading = 'きょうしはがくせいにちしきをおしえる。' where id = '12';
update public.vocabulary set example_reading = 'かんごしはかんじゃのせわをする。' where id = '13';
update public.vocabulary set example_reading = 'やくざいしはしょほうせんをちょうざいする。' where id = '14';
update public.vocabulary set example_reading = 'はいしゃははをちりょうする。' where id = '15';
update public.vocabulary set example_reading = 'りょうりじんはおいしいしょくじをつくる。' where id = '16';
update public.vocabulary set example_reading = 'うんてんしゅはたくしーをうんてんする。' where id = '17';
update public.vocabulary set example_reading = 'ぱいろっとはひこうきをそうじゅうする。' where id = '18';
update public.vocabulary set example_reading = 'のうみんはさくもつをさいばいする。' where id = '19';
update public.vocabulary set example_reading = 'りょうしはさかなをほかくする。' where id = '20';
update public.vocabulary set example_reading = 'しょうにんはしょうひんをばいばいする。' where id = '21';
update public.vocabulary set example_reading = 'ぎんこうかはきんゆうをかんりする。' where id = '22';
update public.vocabulary set example_reading = 'かいけいしはちょうぼをかんりする。' where id = '23';
update public.vocabulary set example_reading = 'けいえいしゃはかいしゃをうんえいする。' where id = '24';
update public.vocabulary set example_reading = 'しゃちょうはかいしゃのさいこうせきにんしゃである。' where id = '25';
update public.vocabulary set example_reading = 'ぶちょうはぶしょをかんりする。' where id = '26';
update public.vocabulary set example_reading = 'かちょうはかをとうかつする。' where id = '27';
update public.vocabulary set example_reading = 'じょうしにほうこくする。' where id = '28';
update public.vocabulary set example_reading = 'じょうしはぶかをしどうする。' where id = '29';
update public.vocabulary set example_reading = 'どうりょうときょうりょくしてしごとをする。' where id = '30';
update public.vocabulary set example_reading = 'こもんとしてけいえいをさぽーとする。' where id = '31';
update public.vocabulary set example_reading = 'こんさるたんとはせんりゃくをていあんする。' where id = '32';
update public.vocabulary set example_reading = 'こうしょうじんはりょうしゃのごういをけいせいする。' where id = '33';
update public.vocabulary set example_reading = 'ちゅうかいじんはりょうしゃをつなぐ。' where id = '34';
update public.vocabulary set example_reading = 'えいぎょうはあたらしいこきゃくをかいたくする。' where id = '35';
update public.vocabulary set example_reading = 'えいぎょうまんはしょうひんをはんばいする。' where id = '36';
update public.vocabulary set example_reading = 'マーケターはしじょうをぶんせきする。' where id = '37';
update public.vocabulary set example_reading = 'こうほうはきぎょうのじょうほうをはっしんする。' where id = '38';
update public.vocabulary set example_reading = 'きかくはあたらしいぷろじぇくとをりつあんする。' where id = '39';
update public.vocabulary set example_reading = 'ひしょはしゃちょうのしごとをさぽーとする。' where id = '40';
update public.vocabulary set example_reading = 'へんしゅうしゃはげんこうをこうせいする。' where id = '41';
update public.vocabulary set example_reading = 'ほんやくしゃはぶんしょうをべつのげんごにやくす。' where id = '42';
update public.vocabulary set example_reading = 'つうやくしゃはかいぎでことばをやくす。' where id = '43';
update public.vocabulary set example_reading = 'けいさつかんはちあんをまもる。' where id = '44';
update public.vocabulary set example_reading = 'しょうぼうしはかさいをけす。' where id = '45';
update public.vocabulary set example_reading = 'へいしはくにをまもる。' where id = '46';
update public.vocabulary set example_reading = 'せいじかはくにのせいさくをりつあんする。' where id = '47';
update public.vocabulary set example_reading = 'ぎいんはこっかいでとうひょうする。' where id = '48';
update public.vocabulary set example_reading = 'ちじはとどうふけんをとうちする。' where id = '49';
update public.vocabulary set example_reading = 'しちょうはとしをとうちする。' where id = '50';
update public.vocabulary set example_reading = 'だいじんはせいふのいちいんである。' where id = '51';
update public.vocabulary set example_reading = 'たいしはくにをだいひょうする。' where id = '52';
update public.vocabulary set example_reading = 'がいこうかんはこくさいこうしょうをする。' where id = '53';
update public.vocabulary set example_reading = 'かんりょうはせいふのぎょうせいをたんとうする。' where id = '54';
update public.vocabulary set example_reading = 'こうむいんはこっかのぎょうむをおこなう。' where id = '55';
update public.vocabulary set example_reading = 'はんじはさいばんではんけつをくだす。' where id = '56';
update public.vocabulary set example_reading = 'けんさつかんははんざいをきそする。' where id = '57';
update public.vocabulary set example_reading = 'べんごしはほうていでいらいじんをだいりする。' where id = '58';
update public.vocabulary set example_reading = 'しょうにんはほうていでしょうげんする。' where id = '59';
update public.vocabulary set example_reading = 'ひこくじんはむざいをしゅちょうする。' where id = '60';
update public.vocabulary set example_reading = 'げんこくはそしょうをおこす。' where id = '61';
update public.vocabulary set example_reading = 'ばいしんいんははんけつをきめる。' where id = '62';
update public.vocabulary set example_reading = 'かんこうがいどはかんこうきゃくをあんないする。' where id = '63';
update public.vocabulary set example_reading = 'ほてるまんはげすとをおもてなしする。' where id = '64';
update public.vocabulary set example_reading = 'うぇいたーはてーぶるにりょうりをはこぶ。' where id = '65';
update public.vocabulary set example_reading = 'バーテンダーはかくてるをつくる。' where id = '66';
update public.vocabulary set example_reading = 'せいそういんはびるをせいそうする。' where id = '67';
update public.vocabulary set example_reading = 'はいそういんはにもつをとどける。' where id = '68';
update public.vocabulary set example_reading = 'ゆうびんはいたつじんはてがみをはいたつする。' where id = '69';
update public.vocabulary set example_reading = 'でんきこうじしはでんきをしこうする。' where id = '70';
update public.vocabulary set example_reading = 'はいかんこうはすいどうをしゅうりする。' where id = '71';
update public.vocabulary set example_reading = 'だいくはいえをけんせつする。' where id = '72';
update public.vocabulary set example_reading = 'ようせつこうははがねをようせつする。' where id = '73';
update public.vocabulary set example_reading = 'きかいこうはきかいをそうさする。' where id = '74';
update public.vocabulary set example_reading = 'ぞうせんこうはふねをけんせつする。' where id = '75';
update public.vocabulary set example_reading = 'てっこうはてつせいひんをせいぞうする。' where id = '76';
update public.vocabulary set example_reading = 'さいくつしゃはこうぶつをほる。' where id = '77';
update public.vocabulary set example_reading = 'こうふはたんこうではたらく。' where id = '78';
update public.vocabulary set example_reading = 'せいぞうこうはせいひんをせいぞうする。' where id = '79';
update public.vocabulary set example_reading = 'こうじょうろうどうしゃはらいんではたらく。' where id = '80';
update public.vocabulary set example_reading = 'のうぎょうじゅうじしゃはのうさくもつをさいばいする。' where id = '81';
update public.vocabulary set example_reading = 'えんげいかはしょくぶつをさいばいする。' where id = '82';
update public.vocabulary set example_reading = 'りんぎょうじゅうじしゃはしんりんをかんりする。' where id = '83';
update public.vocabulary set example_reading = 'じゅういはどうぶつをちりょうする。' where id = '84';
update public.vocabulary set example_reading = 'ペットシッターはぺっとのせわをする。' where id = '85';
update public.vocabulary set example_reading = 'とれーなーはアスリートをしどうする。' where id = '86';
update public.vocabulary set example_reading = 'コーチはちーむをしどうする。' where id = '87';
update public.vocabulary set example_reading = 'すぽーつせんしゅはたいかいにしゅつじょうする。' where id = '88';
update public.vocabulary set example_reading = 'だんさーはぶたいでおどる。' where id = '89';
update public.vocabulary set example_reading = 'ばれえだんさーはばれえをおどる。' where id = '90';
update public.vocabulary set example_reading = 'えんぎしゃはぶたいでえんぎする。' where id = '91';
update public.vocabulary set example_reading = 'はいゆうはえいがにしゅつえんする。' where id = '92';
update public.vocabulary set example_reading = 'じょゆうはえいがにしゅつえんする。' where id = '93';
update public.vocabulary set example_reading = 'せいゆうはあにめでこえをたんとうする。' where id = '94';
update public.vocabulary set example_reading = 'えいがかんとくはえいがをせいさくする。' where id = '95';
update public.vocabulary set example_reading = 'ほうそうさっかはてれびばんぐみをしっぴつする。' where id = '96';
update public.vocabulary set example_reading = 'きゃくほんかはどらまのきゃくほんをかく。' where id = '97';
update public.vocabulary set example_reading = 'えいぞうクリエイターはどうがをせいさくする。' where id = '98';
update public.vocabulary set example_reading = 'かめらまんはしゃしんをさつえいする。' where id = '99';
update public.vocabulary set example_reading = 'しゃしんかはふうけいをさつえいする。' where id = '100';
update public.vocabulary set example_reading = 'むずかしいがいねんをりかいする。' where id = '101';
update public.vocabulary set example_reading = 'でーたをぶんせきする。' where id = '102';
update public.vocabulary set example_reading = 'あたらしいぎじゅつをけんきゅうする。' where id = '103';
update public.vocabulary set example_reading = 'じゅうようなじじつをはっけんする。' where id = '104';
update public.vocabulary set example_reading = 'りろんをけんしょうする。' where id = '105';
update public.vocabulary set example_reading = 'もんだいをふかくこうさつする。' where id = '106';
update public.vocabulary set example_reading = 'ぶんしょうをただしくかいしゃくする。' where id = '107';
update public.vocabulary set example_reading = 'じょうきょうからすいそくする。' where id = '108';
update public.vocabulary set example_reading = 'ひとつのかていにもとづいてかんがえる。' where id = '109';
update public.vocabulary set example_reading = 'じっけんでりろんをじっしょうする。' where id = '110';
update public.vocabulary set example_reading = 'じじつをあきらかにする。' where id = '111';
update public.vocabulary set example_reading = 'ちょうさけっかからけつろんする。' where id = '112';
update public.vocabulary set example_reading = 'じゅうようなぽいんとをそうかつする。' where id = '113';
update public.vocabulary set example_reading = 'ぷろじぇくとのせいかをひょうかする。' where id = '114';
update public.vocabulary set example_reading = 'てきせつにはんだんする。' where id = '115';
update public.vocabulary set example_reading = 'ていあんをくわしくけんとうする。' where id = '116';
update public.vocabulary set example_reading = 'しじょうをちょうさする。' where id = '117';
update public.vocabulary set example_reading = 'げんしょうをかんさつする。' where id = '118';
update public.vocabulary set example_reading = 'ふたつのしょうひんをひかくする。' where id = '119';
update public.vocabulary set example_reading = 'でーたをぶんるいする。' where id = '120';
update public.vocabulary set example_reading = 'うりあげをとうけいする。' where id = '121';
update public.vocabulary set example_reading = 'そうがくをけいさんする。' where id = '122';
update public.vocabulary set example_reading = 'かいしゃではたらく。' where id = '123';
update public.vocabulary set example_reading = 'あたらしいじゅうぎょういんをこようする。' where id = '124';
update public.vocabulary set example_reading = 'あたらしいほうほうをさいようする。' where id = '125';
update public.vocabulary set example_reading = 'ぷろじぇくとをかんりする。' where id = '126';
update public.vocabulary set example_reading = 'がくせいをしどうする。' where id = '127';
update public.vocabulary set example_reading = 'しんにゅうしゃいんをくんれんする。' where id = '128';
update public.vocabulary set example_reading = 'こうじをかんとくする。' where id = '129';
update public.vocabulary set example_reading = 'ぶもんをとうかつする。' where id = '130';
update public.vocabulary set example_reading = 'いべんとをそしきする。' where id = '131';
update public.vocabulary set example_reading = 'びじねすをうんえいする。' where id = '132';
update public.vocabulary set example_reading = 'れすとらんをけいえいする。' where id = '133';
update public.vocabulary set example_reading = 'じぎょうをはってんさせる。' where id = '134';
update public.vocabulary set example_reading = 'ひんしつをかいぜんする。' where id = '135';
update public.vocabulary set example_reading = 'ひんしつをいじする。' where id = '136';
update public.vocabulary set example_reading = 'しんしょうひんをかいはつする。' where id = '137';
update public.vocabulary set example_reading = 'しょうひんをはんばいする。' where id = '138';
update public.vocabulary set example_reading = 'ひつようなものをこうにゅうする。' where id = '139';
update public.vocabulary set example_reading = 'でんりょくをきょうきゅうする。' where id = '140';
update public.vocabulary set example_reading = 'しげんをしょうひする。' where id = '141';
update public.vocabulary set example_reading = 'あたらしいぷろじぇくとにとうしする。' where id = '142';
update public.vocabulary set example_reading = 'じぎょうをゆうしする。' where id = '143';
update public.vocabulary set example_reading = 'おかねをかす。' where id = '144';
update public.vocabulary set example_reading = 'ゆうじんからおかねをかりる。' where id = '145';
update public.vocabulary set example_reading = 'さーびすとけいやくする。' where id = '146';
update public.vocabulary set example_reading = 'かかくについてこうしょうする。' where id = '147';
update public.vocabulary set example_reading = 'じょうけんにごういする。' where id = '148';
update public.vocabulary set example_reading = 'ていあんをりょうしょうする。' where id = '149';
update public.vocabulary set example_reading = 'けいかくをしょうにんする。' where id = '150';
update public.vocabulary set example_reading = 'もうしでをきょひする。' where id = '151';
update public.vocabulary set example_reading = 'しんちょくじょうきょうをほうこくする。' where id = '152';
update public.vocabulary set example_reading = 'きんきゅうでれんらくする。' where id = '153';
update public.vocabulary set example_reading = 'けっかをつうちする。' where id = '154';
update public.vocabulary set example_reading = 'くわしくせつめいする。' where id = '155';
update public.vocabulary set example_reading = 'もんだいてんをしてきする。' where id = '156';
update public.vocabulary set example_reading = 'あたらしいあいであをていあんする。' where id = '157';
update public.vocabulary set example_reading = 'どくしょをすすめる。' where id = '158';
update public.vocabulary set example_reading = 'じゅうぎょういんにしじする。' where id = '159';
update public.vocabulary set example_reading = 'ぶたいにめいじる。' where id = '160';
update public.vocabulary set example_reading = 'きつえんをきんしする。' where id = '161';
update public.vocabulary set example_reading = 'けいかくをきょかする。' where id = '162';
update public.vocabulary set example_reading = 'よろこびをかんじる。' where id = '163';
update public.vocabulary set example_reading = 'よいかんがえだとおもう。' where id = '164';
update public.vocabulary set example_reading = 'ひとをしんじる。' where id = '165';
update public.vocabulary set example_reading = 'ぶかをしんらいする。' where id = '166';
update public.vocabulary set example_reading = 'そのはなしをうたがう。' where id = '167';
update public.vocabulary set example_reading = 'よいけっかをきたいする。' where id = '168';
update public.vocabulary set example_reading = 'せいこうをのぞむ。' where id = '169';
update public.vocabulary set example_reading = 'しあわせをねがう。' where id = '170';
update public.vocabulary set example_reading = 'かぞくのけんこうをしんぱいする。' where id = '171';
update public.vocabulary set example_reading = 'こんごのはってんをけねんする。' where id = '172';
update public.vocabulary set example_reading = 'かぞくをあいする。' where id = '173';
update public.vocabulary set example_reading = 'どくしょがすきだ。' where id = '174';
update public.vocabulary set example_reading = 'むしがいやだ。' where id = '175';
update public.vocabulary set example_reading = 'ふせいをにくむ。' where id = '176';
update public.vocabulary set example_reading = 'せんせいをそんけいする。' where id = '177';
update public.vocabulary set example_reading = 'うやまうきもちをもつ。' where id = '178';
update public.vocabulary set example_reading = 'たしゃをけいべつする。' where id = '179';
update public.vocabulary set example_reading = 'こまっているひとをたすける。' where id = '180';
update public.vocabulary set example_reading = 'ぷろじぇくとをしえんする。' where id = '181';
update public.vocabulary set example_reading = 'せんしゅをおうえんする。' where id = '182';
update public.vocabulary set example_reading = 'ゆうじんをはげます。' where id = '183';
update public.vocabulary set example_reading = 'かなしんでいるひとをなぐさめる。' where id = '184';
update public.vocabulary set example_reading = 'がんばるようはげましかはげます。' where id = '185';
update public.vocabulary set example_reading = 'よいしごとをほめる。' where id = '186';
update public.vocabulary set example_reading = 'がんばりをほめる。' where id = '187';
update public.vocabulary set example_reading = 'けいかくをひはんする。' where id = '188';
update public.vocabulary set example_reading = 'ふせいをひなんする。' where id = '189';
update public.vocabulary set example_reading = 'あやまりをせめる。' where id = '190';
update public.vocabulary set example_reading = 'あやまちをしゃざいする。' where id = '191';
update public.vocabulary set example_reading = 'ふべんをおかけしてわびる。' where id = '192';
update public.vocabulary set example_reading = 'あやまちをゆるす。' where id = '193';
update public.vocabulary set example_reading = 'ふせいにおこる。' where id = '194';
update public.vocabulary set example_reading = 'じょうだんにわらう。' where id = '195';
update public.vocabulary set example_reading = 'かなしくてなく。' where id = '196';
update public.vocabulary set example_reading = 'せいこうをよろこぶ。' where id = '197';
update public.vocabulary set example_reading = 'わかれをかなしむ。' where id = '198';
update public.vocabulary set example_reading = 'よきしないけっかにおどろく。' where id = '199';
update public.vocabulary set example_reading = 'しっぱいをおそれる。' where id = '200';
update public.vocabulary set example_reading = 'げんだいしゃかいはふくざつです。' where id = 'N4_0001';
update public.vocabulary set example_reading = 'いしゃにみてもらいました。' where id = 'N4_0002';
update public.vocabulary set example_reading = 'おおきなかいしゃにつとめています。' where id = 'N4_0003';
update public.vocabulary set example_reading = 'しごとがいそがしいです。' where id = 'N4_0004';
update public.vocabulary set example_reading = 'まいにちはたらいています。' where id = 'N4_0005';
update public.vocabulary set example_reading = 'べんきょうをしています。' where id = 'N4_0006';
update public.vocabulary set example_reading = 'このもんだいはむずかしいです。' where id = 'N4_0007';
update public.vocabulary set example_reading = 'このもんだいはかんたんです。' where id = 'N4_0008';
update public.vocabulary set example_reading = 'じょうきょうはふくざつです。' where id = 'N4_0009';
update public.vocabulary set example_reading = 'これはじゅうようなかいぎです。' where id = 'N4_0010';
update public.vocabulary set example_reading = 'りかいできました。' where id = 'N4_0011';
update public.vocabulary set example_reading = 'でーたをぶんせきします。' where id = 'N4_0012';
update public.vocabulary set example_reading = 'にっぽんぶんかをけんきゅうしています。' where id = 'N4_0013';
update public.vocabulary set example_reading = 'ちしきがたいせつです。' where id = 'N4_0014';
update public.vocabulary set example_reading = 'にっぽんぶんかはきょうみぶかいです。' where id = 'N4_0015';
update public.vocabulary set example_reading = 'あたらしいぎじゅつがかいはつされました。' where id = 'N4_0016';
update public.vocabulary set example_reading = 'あたたかさをかんじます。' where id = 'N4_0017';
update public.vocabulary set example_reading = 'そうおもいます。' where id = 'N4_0018';
update public.vocabulary set example_reading = 'かれをしんじています。' where id = 'N4_0019';
update public.vocabulary set example_reading = 'みらいへのきぼうがあります。' where id = 'N4_0020';
update public.vocabulary set example_reading = 'けっしんしてべんきょうします。' where id = 'N4_V_001';
update public.vocabulary set example_reading = 'どりょくしてせいこうしました。' where id = 'N4_V_002';
update public.vocabulary set example_reading = 'あたらしいちょうせんをします。' where id = 'N4_V_003';
update public.vocabulary set example_reading = 'ぷろじぇくとがせいこうしました。' where id = 'N4_V_004';
update public.vocabulary set example_reading = 'いちどのしっぱいであきらめません。' where id = 'N4_V_005';
update public.vocabulary set example_reading = 'けいかくをたてます。' where id = 'N4_V_006';
update public.vocabulary set example_reading = 'もくひょうをたっせいしました。' where id = 'N4_V_007';
update public.vocabulary set example_reading = 'ほうふなけいけんがあります。' where id = 'N4_V_008';
update public.vocabulary set example_reading = 'のうりょくがたかいです。' where id = 'N4_V_009';
update public.vocabulary set example_reading = 'ぎじゅつがひつようです。' where id = 'N4_V_010';
update public.vocabulary set example_reading = 'ちしきをひろめます。' where id = 'N4_V_011';
update public.vocabulary set example_reading = 'ちえがひつようです。' where id = 'N4_V_012';
update public.vocabulary set example_reading = 'くふうがひつようです。' where id = 'N4_V_013';
update public.vocabulary set example_reading = 'あたらしいはつめいがあります。' where id = 'N4_V_014';
update public.vocabulary set example_reading = 'あたらしいはっけんがあります。' where id = 'N4_V_015';
update public.vocabulary set example_reading = 'けんきゅうをしています。' where id = 'N4_V_016';
update public.vocabulary set example_reading = 'ちょうさをおこないます。' where id = 'N4_V_017';
update public.vocabulary set example_reading = 'しつもんがあります。' where id = 'N4_V_018';
update public.vocabulary set example_reading = 'こたえがわかりません。' where id = 'N4_V_019';
update public.vocabulary set example_reading = 'せつめいをします。' where id = 'N4_V_020';
update public.vocabulary set example_reading = 'いけんをいいます。' where id = 'N4_V_021';
update public.vocabulary set example_reading = 'ていあんがあります。' where id = 'N4_V_022';
update public.vocabulary set example_reading = 'はんだんがひつようです。' where id = 'N4_V_023';
update public.vocabulary set example_reading = 'けっていをくだします。' where id = 'N4_V_024';
update public.vocabulary set example_reading = 'きょかをえます。' where id = 'N4_V_025';
update public.vocabulary set example_reading = 'きんしされています。' where id = 'N4_V_026';
update public.vocabulary set example_reading = 'けいこくをうけました。' where id = 'N4_V_027';
update public.vocabulary set example_reading = 'しじにしたがいます。' where id = 'N4_V_028';
update public.vocabulary set example_reading = 'めいれいにしたがいます。' where id = 'N4_V_029';
update public.vocabulary set example_reading = 'そうだんがあります。' where id = 'N4_V_030';
update public.vocabulary set example_reading = 'じょげんをもらいます。' where id = 'N4_V_031';
update public.vocabulary set example_reading = 'きょうりょくをおねがいします。' where id = 'N4_V_032';
update public.vocabulary set example_reading = 'きょうそうにさんかします。' where id = 'N4_V_033';
update public.vocabulary set example_reading = 'たいこうします。' where id = 'N4_V_034';
update public.vocabulary set example_reading = 'せんそうはわるいです。' where id = 'N4_V_035';
update public.vocabulary set example_reading = 'へいわをねがいます。' where id = 'N4_V_036';
update public.vocabulary set example_reading = 'ふんそうをかいけつします。' where id = 'N4_V_037';
update public.vocabulary set example_reading = 'もんだいがあります。' where id = 'N4_V_038';
update public.vocabulary set example_reading = 'かだいがあります。' where id = 'N4_V_039';
update public.vocabulary set example_reading = 'しょうがいがあります。' where id = 'N4_V_040';
update public.vocabulary set example_reading = 'こんなんがあります。' where id = 'N4_V_041';
update public.vocabulary set example_reading = 'きけんがあります。' where id = 'N4_V_042';
update public.vocabulary set example_reading = 'あんぜんがだいじです。' where id = 'N4_V_043';
update public.vocabulary set example_reading = 'じこがおこりました。' where id = 'N4_V_044';
update public.vocabulary set example_reading = 'さいがいがおこりました。' where id = 'N4_V_045';
update public.vocabulary set example_reading = 'じしんがおこりました。' where id = 'N4_V_046';
update public.vocabulary set example_reading = 'たいふうがきます。' where id = 'N4_V_047';
update public.vocabulary set example_reading = 'こうずいがおこりました。' where id = 'N4_V_048';
update public.vocabulary set example_reading = 'かじがおこりました。' where id = 'N4_V_049';
update public.vocabulary set example_reading = 'かぜをひきました。' where id = 'N4_V_050';
update public.vocabulary set example_reading = 'こうぎょうがはったつしました。' where id = 'N4_V_051';
update public.vocabulary set example_reading = 'のうぎょうがだいじです。' where id = 'N4_V_052';
update public.vocabulary set example_reading = 'しょうぎょうがはってんしました。' where id = 'N4_V_053';
update public.vocabulary set example_reading = 'さんぎょうがじゅうようです。' where id = 'N4_V_054';
update public.vocabulary set example_reading = 'かいしゃにはたらいています。' where id = 'N4_V_055';
update public.vocabulary set example_reading = 'おおきなきぎょうです。' where id = 'N4_V_056';
update public.vocabulary set example_reading = 'そしきがおおきいです。' where id = 'N4_V_057';
update public.vocabulary set example_reading = 'きこうがふくざつです。' where id = 'N4_V_058';
update public.vocabulary set example_reading = 'せいどがかわりました。' where id = 'N4_V_059';
update public.vocabulary set example_reading = 'ほうりつをまもります。' where id = 'N4_V_060';
update public.vocabulary set example_reading = 'けんりがあります。' where id = 'N4_V_061';
update public.vocabulary set example_reading = 'ぎむがあります。' where id = 'N4_V_062';
update public.vocabulary set example_reading = 'せきにんがあります。' where id = 'N4_V_063';
update public.vocabulary set example_reading = 'しんようをえます。' where id = 'N4_V_064';
update public.vocabulary set example_reading = 'しんらいがあります。' where id = 'N4_V_065';
update public.vocabulary set example_reading = 'りんりがだいじです。' where id = 'N4_V_066';
update public.vocabulary set example_reading = 'どうとくがたいせつです。' where id = 'N4_V_067';
update public.vocabulary set example_reading = 'かちがあります。' where id = 'N4_V_068';
update public.vocabulary set example_reading = 'いみがわかりません。' where id = 'N4_V_069';
update public.vocabulary set example_reading = 'もくてきがあります。' where id = 'N4_V_070';
update public.vocabulary set example_reading = 'ねがいがあります。' where id = 'N4_V_071';
update public.vocabulary set example_reading = 'きぼうがあります。' where id = 'N4_V_072';
update public.vocabulary set example_reading = 'ぜつぼうしました。' where id = 'N4_V_073';
update public.vocabulary set example_reading = 'こいをしています。' where id = 'N4_V_074';
update public.vocabulary set example_reading = 'あいがだいじです。' where id = 'N4_V_075';
update public.vocabulary set example_reading = 'よろこびをかんじます。' where id = 'N4_V_076';
update public.vocabulary set example_reading = 'かなしみをかんじます。' where id = 'N4_V_077';
update public.vocabulary set example_reading = 'いかりをかんじます。' where id = 'N4_V_078';
update public.vocabulary set example_reading = 'きょうふをかんじます。' where id = 'N4_V_079';
update public.vocabulary set example_reading = 'おどろきをかくせません。' where id = 'N4_V_080';
update public.vocabulary set example_reading = 'わたしはがくせいです。' where id = 'N5_0001';
update public.vocabulary set example_reading = 'せんせいはしんせつです。' where id = 'N5_0002';
update public.vocabulary set example_reading = 'わたしはまいにちがっこうにいきます。' where id = 'N5_0003';
update public.vocabulary set example_reading = 'きょうしつはひろいです。' where id = 'N5_0004';
update public.vocabulary set example_reading = 'わたしはほんがすきです。' where id = 'N5_0005';
update public.vocabulary set example_reading = 'つくえのうえにほんがあります。' where id = 'N5_0006';
update public.vocabulary set example_reading = 'いすにすわってください。' where id = 'N5_0007';
update public.vocabulary set example_reading = 'こくばんにもじをかきます。' where id = 'N5_0008';
update public.vocabulary set example_reading = 'あさごはんをたべます。' where id = 'N5_0009';
update public.vocabulary set example_reading = 'みずをのみます。' where id = 'N5_0010';
update public.vocabulary set example_reading = 'こめをたべます。' where id = 'N5_0011';
update public.vocabulary set example_reading = 'あさぱんをたべます。' where id = 'N5_0012';
update public.vocabulary set example_reading = 'にくはおいしいです。' where id = 'N5_0013';
update public.vocabulary set example_reading = 'さかながすきです。' where id = 'N5_0014';
update public.vocabulary set example_reading = 'やさいはけんこうてきです。' where id = 'N5_0015';
update public.vocabulary set example_reading = 'くだものはあまいです。' where id = 'N5_0016';
update public.vocabulary set example_reading = 'しろいしゃつをきます。' where id = 'N5_0017';
update public.vocabulary set example_reading = 'くろいずぼんをもっています。' where id = 'N5_0018';
update public.vocabulary set example_reading = 'あたらしいくつをかいました。' where id = 'N5_0019';
update public.vocabulary set example_reading = 'ぼうしをかぶります。' where id = 'N5_0020';
update public.vocabulary set example_reading = 'あたまがいたいです。' where id = 'N5_0021';
update public.vocabulary set example_reading = 'めがおおきいです。' where id = 'N5_0022';
update public.vocabulary set example_reading = 'みみがきこえません。' where id = 'N5_0023';
update public.vocabulary set example_reading = 'はながたかいです。' where id = 'N5_0024';
update public.vocabulary set example_reading = 'くちをあけてください。' where id = 'N5_0025';
update public.vocabulary set example_reading = 'てをあげてください。' where id = 'N5_0026';
update public.vocabulary set example_reading = 'あしがいたいです。' where id = 'N5_0027';
update public.vocabulary set example_reading = 'こころがいたいです。' where id = 'N5_0028';
update public.vocabulary set example_reading = 'からだがけんこうです。' where id = 'N5_0029';
update public.vocabulary set example_reading = 'べっどでねます。' where id = 'N5_0030';
update public.vocabulary set example_reading = 'わたしはがくせいです。' where id = 'N5_V_001';
update public.vocabulary set example_reading = 'せんせいはしんせつです。' where id = 'N5_V_002';
update public.vocabulary set example_reading = 'がっこうへいきます。' where id = 'N5_V_003';
update public.vocabulary set example_reading = 'いえにかえります。' where id = 'N5_V_004';
update public.vocabulary set example_reading = 'ひとがおおいです。' where id = 'N5_V_005';
update public.vocabulary set example_reading = 'ともだちとあそびます。' where id = 'N5_V_006';
update public.vocabulary set example_reading = 'わたしのなまえはタロウです。' where id = 'N5_V_007';
update public.vocabulary set example_reading = 'たべものがすきです。' where id = 'N5_V_008';
update public.vocabulary set example_reading = 'ごはんをたべます。' where id = 'N5_V_009';
update public.vocabulary set example_reading = 'みずをのみます。' where id = 'N5_V_010';
update public.vocabulary set example_reading = 'にくがすきです。' where id = 'N5_V_011';
update public.vocabulary set example_reading = 'さかなをたべます。' where id = 'N5_V_012';
update public.vocabulary set example_reading = 'やさいをたべます。' where id = 'N5_V_013';
update public.vocabulary set example_reading = 'くだものがすきです。' where id = 'N5_V_014';
update public.vocabulary set example_reading = 'あさはぱんをたべます。' where id = 'N5_V_015';
update public.vocabulary set example_reading = 'ぎゅうにゅうをのみます。' where id = 'N5_V_016';
update public.vocabulary set example_reading = 'たまごをやきます。' where id = 'N5_V_017';
update public.vocabulary set example_reading = 'しおをいれます。' where id = 'N5_V_018';
update public.vocabulary set example_reading = 'さとうがあまいです。' where id = 'N5_V_019';
update public.vocabulary set example_reading = 'しょうゆをかけます。' where id = 'N5_V_020';
update public.vocabulary set example_reading = 'あさにおきます。' where id = 'N5_V_021';
update public.vocabulary set example_reading = 'ひるにたべます。' where id = 'N5_V_022';
update public.vocabulary set example_reading = 'ばんにいえにかえります。' where id = 'N5_V_023';
update public.vocabulary set example_reading = 'よるにねます。' where id = 'N5_V_024';
update public.vocabulary set example_reading = 'げつようびにあいましょう。' where id = 'N5_V_025';
update public.vocabulary set example_reading = 'かようびです。' where id = 'N5_V_026';
update public.vocabulary set example_reading = 'すいようびにじゅぎょうがあります。' where id = 'N5_V_027';
update public.vocabulary set example_reading = 'もくようびにかいぎがあります。' where id = 'N5_V_028';
update public.vocabulary set example_reading = 'きんようびはたのしいです。' where id = 'N5_V_029';
update public.vocabulary set example_reading = 'どようびにあそびます。' where id = 'N5_V_030';
update public.vocabulary set example_reading = 'にちようびはいえにいます。' where id = 'N5_V_031';
update public.vocabulary set example_reading = 'いちがつはさむいです。' where id = 'N5_V_032';
update public.vocabulary set example_reading = 'にがつはみじかいです。' where id = 'N5_V_033';
update public.vocabulary set example_reading = 'さんがつははるです。' where id = 'N5_V_034';
update public.vocabulary set example_reading = 'しがつはさくらがさきます。' where id = 'N5_V_035';
update public.vocabulary set example_reading = 'ごがつはあたたかいです。' where id = 'N5_V_036';
update public.vocabulary set example_reading = 'ろくがつはあめがおおいです。' where id = 'N5_V_037';
update public.vocabulary set example_reading = 'しちがつはあついです。' where id = 'N5_V_038';
update public.vocabulary set example_reading = 'はちがつはなつやすみです。' where id = 'N5_V_039';
update public.vocabulary set example_reading = 'くがつはあきです。' where id = 'N5_V_040';
update public.vocabulary set example_reading = 'じゅうがつはすずしいです。' where id = 'N5_V_041';
update public.vocabulary set example_reading = 'じゅういちがつはさむくなります。' where id = 'N5_V_042';
update public.vocabulary set example_reading = 'じゅうにがつはくりすますです。' where id = 'N5_V_043';
update public.vocabulary set example_reading = 'いちにちはつきのはじまりです。' where id = 'N5_V_044';
update public.vocabulary set example_reading = 'ににちにあいます。' where id = 'N5_V_045';
update public.vocabulary set example_reading = 'さんにちごにきます。' where id = 'N5_V_046';
update public.vocabulary set example_reading = 'よんにちかんいます。' where id = 'N5_V_047';
update public.vocabulary set example_reading = 'ごにちでおわります。' where id = 'N5_V_048';
update public.vocabulary set example_reading = 'じゅうにちにしゅうごうします。' where id = 'N5_V_049';
update public.vocabulary set example_reading = 'にじゅうにちにしゅっぱつします。' where id = 'N5_V_050';
update public.vocabulary set example_reading = 'べんきょうします。' where id = 'N5_V_051';
update public.vocabulary set example_reading = 'しごとがいそがしいです。' where id = 'N5_V_052';
update public.vocabulary set example_reading = 'あそびにいきます。' where id = 'N5_V_053';
update public.vocabulary set example_reading = 'やすみがほしいです。' where id = 'N5_V_054';
update public.vocabulary set example_reading = 'びょうきです。' where id = 'N5_V_055';
update public.vocabulary set example_reading = 'けんこうがだいじです。' where id = 'N5_V_056';
update public.vocabulary set example_reading = 'からだがいたいです。' where id = 'N5_V_057';
update public.vocabulary set example_reading = 'あたまがいたいです。' where id = 'N5_V_058';
update public.vocabulary set example_reading = 'めがつかれています。' where id = 'N5_V_059';
update public.vocabulary set example_reading = 'はながつまっています。' where id = 'N5_V_060';
update public.vocabulary set example_reading = 'みみがきこえません。' where id = 'N5_V_061';
update public.vocabulary set example_reading = 'くちがひらいています。' where id = 'N5_V_062';
update public.vocabulary set example_reading = 'はがいたいです。' where id = 'N5_V_063';
update public.vocabulary set example_reading = 'したがみじかいです。' where id = 'N5_V_064';
update public.vocabulary set example_reading = 'のどがいたいです。' where id = 'N5_V_065';
update public.vocabulary set example_reading = 'かたがこっています。' where id = 'N5_V_066';
update public.vocabulary set example_reading = 'うでがつよいです。' where id = 'N5_V_067';
update public.vocabulary set example_reading = 'てがよごれています。' where id = 'N5_V_068';
update public.vocabulary set example_reading = 'ゆびをきりました。' where id = 'N5_V_069';
update public.vocabulary set example_reading = 'あしがつかれています。' where id = 'N5_V_070';
update public.vocabulary set example_reading = 'こころがいたいです。' where id = 'N5_V_071';
update public.vocabulary set example_reading = 'きもちがわるいです。' where id = 'N5_V_072';
update public.vocabulary set example_reading = 'いのちをだいじにします。' where id = 'N5_V_073';
update public.vocabulary set example_reading = 'ふくをきます。' where id = 'N5_V_074';
update public.vocabulary set example_reading = 'くつをはきます。' where id = 'N5_V_075';
update public.vocabulary set example_reading = 'ぼうしをかぶります。' where id = 'N5_V_076';
update public.vocabulary set example_reading = 'めがねをかけます。' where id = 'N5_V_077';
update public.vocabulary set example_reading = 'とけいをみます。' where id = 'N5_V_078';
update public.vocabulary set example_reading = 'かぎをもっています。' where id = 'N5_V_079';
update public.vocabulary set example_reading = 'けいたいでんわをつかいます。' where id = 'N5_V_080';
update public.vocabulary set example_reading = 'ほんをよみます。' where id = 'N5_V_081';
update public.vocabulary set example_reading = 'ざっしをよみます。' where id = 'N5_V_082';
update public.vocabulary set example_reading = 'しんぶんをよみます。' where id = 'N5_V_083';
update public.vocabulary set example_reading = 'てがみをかきます。' where id = 'N5_V_084';
update public.vocabulary set example_reading = 'ゆうびんをおくります。' where id = 'N5_V_085';
update public.vocabulary set example_reading = 'きっぷをかいます。' where id = 'N5_V_086';
update public.vocabulary set example_reading = 'ちずをみます。' where id = 'N5_V_087';
update public.vocabulary set example_reading = 'しゃしんをとります。' where id = 'N5_V_088';
update public.vocabulary set example_reading = 'えをえがきます。' where id = 'N5_V_089';
update public.vocabulary set example_reading = 'えいがをみます。' where id = 'N5_V_090';
update public.vocabulary set example_reading = 'てれびをみます。' where id = 'N5_V_091';
update public.vocabulary set example_reading = 'おんがくをききます。' where id = 'N5_V_092';
update public.vocabulary set example_reading = 'うたをうたいます。' where id = 'N5_V_093';
update public.vocabulary set example_reading = 'ゆうえんちにいきます。' where id = 'N5_V_094';
update public.vocabulary set example_reading = 'すぽーつをします。' where id = 'N5_V_095';
update public.vocabulary set example_reading = 'やきゅうをします。' where id = 'N5_V_096';
update public.vocabulary set example_reading = 'さっかーをします。' where id = 'N5_V_097';
update public.vocabulary set example_reading = 'てにすをします。' where id = 'N5_V_098';
update public.vocabulary set example_reading = 'すいえいをします。' where id = 'N5_V_099';
update public.vocabulary set example_reading = 'えきにいきます。' where id = 'N5_V_100';
