-- Vocabulary seed data: N5 (40 words) + N4 (30 words)

-- Ensure all columns exist (safe to run multiple times)
ALTER TABLE public.vocabulary
  ADD COLUMN IF NOT EXISTS id text,
  ADD COLUMN IF NOT EXISTS level text,
  ADD COLUMN IF NOT EXISTS kanji text,
  ADD COLUMN IF NOT EXISTS reading text,
  ADD COLUMN IF NOT EXISTS pos text,
  ADD COLUMN IF NOT EXISTS meaning_zh text,
  ADD COLUMN IF NOT EXISTS meaning_en text,
  ADD COLUMN IF NOT EXISTS example_ja text,
  ADD COLUMN IF NOT EXISTS example_reading text,
  ADD COLUMN IF NOT EXISTS example_zh text,
  ADD COLUMN IF NOT EXISTS synonyms text[],
  ADD COLUMN IF NOT EXISTS antonyms text[],
  ADD COLUMN IF NOT EXISTS collocations text[],
  ADD COLUMN IF NOT EXISTS conversation_freq text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz;

INSERT INTO public.vocabulary (
  id, level, kanji, reading, pos,
  meaning_zh, meaning_en,
  example_ja, example_reading, example_zh,
  synonyms, antonyms, collocations,
  conversation_freq
) VALUES

-- ============================================================
-- N5 (40 words)
-- ============================================================

('v-001', 'N5', NULL, 'おはよう', '感動詞',
 '早安', 'Good morning',
 'おはよう！今日もいい天気だね。', 'おはよう！きょうもいいてんきだね。', '早安！今天天氣也很好呢。',
 ARRAY['おはようございます'], ARRAY[]::text[], ARRAY['おはようございます', '〜ございます'],
 'very_high'),

('v-002', 'N5', NULL, 'こんにちは', '感動詞',
 '你好（白天的問候）', 'Hello / Good afternoon',
 'こんにちは、田中さん。お元気ですか？', 'こんにちは、たなかさん。おげんきですか？', '你好，田中先生。你還好嗎？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜、元気ですか'],
 'very_high'),

('v-003', 'N5', NULL, 'こんばんは', '感動詞',
 '晚上好', 'Good evening',
 'こんばんは。今夜は寒いですね。', 'こんばんは。こんやはさむいですね。', '晚上好。今晚很冷呢。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜、寒いですね'],
 'very_high'),

('v-004', 'N5', NULL, 'ありがとう', '感動詞',
 '謝謝', 'Thank you',
 'ありがとう！助かったよ。', 'ありがとう！たすかったよ。', '謝謝！幫了大忙了。',
 ARRAY['ありがとうございます'], ARRAY[]::text[], ARRAY['どうも〜', '〜ございます'],
 'very_high'),

('v-005', 'N5', NULL, 'すみません', '感動詞',
 '對不起；不好意思；打擾一下', 'Excuse me / I''m sorry',
 'すみません、ここはどこですか？', 'すみません、ここはどこですか？', '不好意思，請問這裡是哪裡？',
 ARRAY['ごめんなさい'], ARRAY[]::text[], ARRAY['〜、〜てください'],
 'very_high'),

('v-006', 'N5', '一', 'いち', '名詞',
 '一；1', 'One',
 '一つください。', 'ひとつください。', '請給我一個。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜つ', '〜番'],
 'very_high'),

('v-007', 'N5', '百', 'ひゃく', '名詞',
 '一百；100', 'One hundred',
 'これは百円です。', 'これはひゃくえんです。', '這個是一百日圓。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜円', '〜個'],
 'high'),

('v-008', 'N5', '今日', 'きょう', '名詞',
 '今天', 'Today',
 '今日は学校があります。', 'きょうはがっこうがあります。', '今天有上學。',
 ARRAY['本日'], ARRAY['昨日', '明日'], ARRAY['〜は〜があります', '〜の予定'],
 'very_high'),

('v-009', 'N5', '明日', 'あした', '名詞',
 '明天', 'Tomorrow',
 '明日、映画を見に行きます。', 'あした、えいがをみにいきます。', '明天我要去看電影。',
 ARRAY['あす', '明日（みょうにち）'], ARRAY['昨日', '今日'], ARRAY['〜の予定', '〜までに'],
 'very_high'),

('v-010', 'N5', '昨日', 'きのう', '名詞',
 '昨天', 'Yesterday',
 '昨日は雨でした。', 'きのうはあめでした。', '昨天下雨了。',
 ARRAY['昨日（さくじつ）'], ARRAY['今日', '明日'], ARRAY['〜は〜でした'],
 'very_high'),

('v-011', 'N5', '時間', 'じかん', '名詞',
 '時間；時刻', 'Time',
 '時間がありません。', 'じかんがありません。', '沒有時間了。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜がない', '〜をかける'],
 'very_high'),

('v-012', 'N5', '家族', 'かぞく', '名詞',
 '家人；家族', 'Family',
 '家族と一緒に食べます。', 'かぞくといっしょにたべます。', '和家人一起吃飯。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜と一緒に', '〜の写真'],
 'high'),

('v-013', 'N5', '母', 'はは', '名詞',
 '母親（自己的母親）', 'Mother (own)',
 '母は料理が上手です。', 'はははりょうりがじょうずです。', '我媽媽很擅長做料理。',
 ARRAY[]::text[], ARRAY['父'], ARRAY['〜は〜が上手'],
 'high'),

('v-014', 'N5', '父', 'ちち', '名詞',
 '父親（自己的父親）', 'Father (own)',
 '父は会社員です。', 'ちちはかいしゃいんです。', '我爸爸是公司職員。',
 ARRAY[]::text[], ARRAY['母'], ARRAY['〜は〜です'],
 'high'),

('v-015', 'N5', '目', 'め', '名詞',
 '眼睛', 'Eye',
 '目が痛いです。', 'めがいたいです。', '眼睛很痛。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜が痛い', '〜を閉じる'],
 'high'),

('v-016', 'N5', '手', 'て', '名詞',
 '手', 'Hand',
 '手を洗ってください。', 'てをあらってください。', '請洗手。',
 ARRAY[]::text[], ARRAY['足'], ARRAY['〜を洗う', '〜を貸す'],
 'very_high'),

('v-017', 'N5', '食べる', 'たべる', '動詞',
 '吃', 'To eat',
 '毎日ご飯を食べます。', 'まいにちごはんをたべます。', '每天吃飯。',
 ARRAY[]::text[], ARRAY['飲む'], ARRAY['ご飯を〜', 'お菓子を〜'],
 'very_high'),

('v-018', 'N5', '飲む', 'のむ', '動詞',
 '喝；服（藥）', 'To drink',
 '水を飲んでください。', 'みずをのんでください。', '請喝水。',
 ARRAY[]::text[], ARRAY['食べる'], ARRAY['水を〜', 'お茶を〜', '薬を〜'],
 'very_high'),

('v-019', 'N5', '行く', 'いく', '動詞',
 '去', 'To go',
 '学校に行きます。', 'がっこうにいきます。', '去學校。',
 ARRAY[]::text[], ARRAY['来る'], ARRAY['〜に〜', '〜へ〜'],
 'very_high'),

('v-020', 'N5', '来る', 'くる', '動詞',
 '來', 'To come',
 '友達が家に来ます。', 'ともだちがいえにきます。', '朋友來家裡。',
 ARRAY[]::text[], ARRAY['行く'], ARRAY['〜に来る', '〜へ来る'],
 'very_high'),

('v-021', 'N5', '見る', 'みる', '動詞',
 '看；觀看', 'To see / to watch',
 'テレビを見ます。', 'テレビをみます。', '看電視。',
 ARRAY['見物する'], ARRAY[]::text[], ARRAY['テレビを〜', '映画を〜', '〜てみる'],
 'very_high'),

('v-022', 'N5', '聞く', 'きく', '動詞',
 '聽；問', 'To listen / to ask',
 '音楽を聞きます。', 'おんがくをききます。', '聽音樂。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['音楽を〜', '質問を〜', '〜に〜を聞く'],
 'very_high'),

('v-023', 'N5', '話す', 'はなす', '動詞',
 '說；談話', 'To speak / to talk',
 '日本語で話しましょう。', 'にほんごではなしましょう。', '用日語說吧。',
 ARRAY['しゃべる'], ARRAY[]::text[], ARRAY['〜語で〜', '〜と話す'],
 'very_high'),

('v-024', 'N5', '書く', 'かく', '動詞',
 '寫', 'To write',
 '手紙を書きます。', 'てがみをかきます。', '寫信。',
 ARRAY[]::text[], ARRAY['読む'], ARRAY['手紙を〜', '漢字を〜', 'ノートに〜'],
 'high'),

('v-025', 'N5', '読む', 'よむ', '動詞',
 '讀；閱讀', 'To read',
 '本を読むのが好きです。', 'ほんをよむのがすきです。', '我喜歡看書。',
 ARRAY[]::text[], ARRAY['書く'], ARRAY['本を〜', '新聞を〜'],
 'high'),

('v-026', 'N5', '買う', 'かう', '動詞',
 '買', 'To buy',
 'スーパーで野菜を買います。', 'スーパーでやさいをかいます。', '在超市買蔬菜。',
 ARRAY[]::text[], ARRAY['売る'], ARRAY['〜で〜を買う', '〜を買いに行く'],
 'very_high'),

('v-027', 'N5', '売る', 'うる', '動詞',
 '賣', 'To sell',
 'この店では魚を売っています。', 'このみせではさかなをうっています。', '這家店在賣魚。',
 ARRAY[]::text[], ARRAY['買う'], ARRAY['〜を売る', '〜で〜を売る'],
 'medium'),

('v-028', 'N5', '大きい', 'おおきい', 'イ形',
 '大的', 'Big / large',
 'この犬は大きいです。', 'このいぬはおおきいです。', '這隻狗很大。',
 ARRAY[]::text[], ARRAY['小さい'], ARRAY['〜犬', '〜声', '〜家'],
 'very_high'),

('v-029', 'N5', '小さい', 'ちいさい', 'イ形',
 '小的', 'Small / little',
 '小さい花が咲いています。', 'ちいさいはながさいています。', '小花正在盛開。',
 ARRAY[]::text[], ARRAY['大きい'], ARRAY['〜花', '〜子供'],
 'very_high'),

('v-030', 'N5', '新しい', 'あたらしい', 'イ形',
 '新的', 'New',
 '新しい服を買いました。', 'あたらしいふくをかいました。', '買了新衣服。',
 ARRAY[]::text[], ARRAY['古い'], ARRAY['〜服', '〜車', '〜友達'],
 'very_high'),

('v-031', 'N5', '古い', 'ふるい', 'イ形',
 '舊的', 'Old',
 'この建物は古いです。', 'このたてものはふるいです。', '這棟建築物很舊。',
 ARRAY[]::text[], ARRAY['新しい'], ARRAY['〜建物', '〜車', '〜本'],
 'high'),

('v-032', 'N5', '高い', 'たかい', 'イ形',
 '貴的；高的', 'Expensive / tall',
 'このレストランは高いですね。', 'このレストランはたかいですね。', '這家餐廳很貴呢。',
 ARRAY[]::text[], ARRAY['安い', '低い'], ARRAY['値段が〜', '山が〜'],
 'very_high'),

('v-033', 'N5', '安い', 'やすい', 'イ形',
 '便宜的', 'Cheap / inexpensive',
 'このお店は安くておいしいです。', 'このおみせはやすくておいしいです。', '這家店便宜又好吃。',
 ARRAY[]::text[], ARRAY['高い'], ARRAY['値段が〜', '〜店'],
 'very_high'),

('v-034', 'N5', '好き', 'すき', 'ナ形',
 '喜歡的', 'Liked / fond of',
 '私は音楽が好きです。', 'わたしはおんがくがすきです。', '我喜歡音樂。',
 ARRAY[]::text[], ARRAY['嫌い'], ARRAY['〜な食べ物', '〜な人'],
 'very_high'),

('v-035', 'N5', '嫌い', 'きらい', 'ナ形',
 '討厭的；不喜歡的', 'Disliked',
 '野菜が嫌いな子が多いです。', 'やさいがきらいなこがおおいです。', '有很多不喜歡蔬菜的孩子。',
 ARRAY[]::text[], ARRAY['好き'], ARRAY['〜な食べ物', '〜な人'],
 'very_high'),

('v-036', 'N5', '人', 'ひと', '名詞',
 '人', 'Person / people',
 'あの人は誰ですか？', 'あのひとはだれですか？', '那個人是誰？',
 ARRAY['方（かた）'], ARRAY[]::text[], ARRAY['〜が多い', '〜がいる'],
 'very_high'),

('v-037', 'N5', '水', 'みず', '名詞',
 '水', 'Water',
 '水を一杯ください。', 'みずをいっぱいください。', '請給我一杯水。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を飲む', '〜を入れる'],
 'very_high'),

('v-038', 'N5', 'ご飯', 'ごはん', '名詞',
 '飯；餐食', 'Rice / meal',
 'ご飯を一緒に食べましょう。', 'ごはんをいっしょにたべましょう。', '我們一起吃飯吧。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を食べる', '朝〜', '夜〜'],
 'very_high'),

('v-039', 'N5', '電車', 'でんしゃ', '名詞',
 '電車', 'Train',
 '電車で学校に行きます。', 'でんしゃでがっこうにいきます。', '搭電車去學校。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜に乗る', '〜で行く', '〜に乗り換える'],
 'very_high'),

('v-040', 'N5', '駅', 'えき', '名詞',
 '車站', 'Train station',
 '駅はどこですか？', 'えきはどこですか？', '車站在哪裡？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜で待つ', '〜に着く', '〜の近く'],
 'very_high'),

-- ============================================================
-- N4 (30 words)
-- ============================================================

('v-041', 'N4', '始める', 'はじめる', '動詞',
 '開始；著手', 'To begin / to start',
 '来月から日本語を始めます。', 'らいげつからにほんごをはじめます。', '從下個月開始學日語。',
 ARRAY[]::text[], ARRAY['終わる', '終える'], ARRAY['〜を始める', '〜から始める'],
 'very_high'),

('v-042', 'N4', '終わる', 'おわる', '動詞',
 '結束；完成', 'To end / to finish',
 '仕事が終わったら、電話します。', 'しごとがおわったら、でんわします。', '工作結束後，我會打電話。',
 ARRAY['終える'], ARRAY['始める'], ARRAY['〜が終わる', '〜てから'],
 'very_high'),

('v-043', 'N4', '決める', 'きめる', '動詞',
 '決定；決定下來', 'To decide',
 '今日中に決めてください。', 'きょうじゅうにきめてください。', '請在今天之內做決定。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を決める', '〜に決める'],
 'high'),

('v-044', 'N4', '覚える', 'おぼえる', '動詞',
 '記住；記得；學會', 'To memorize / to remember',
 '単語を覚えるのは大変です。', 'たんごをおぼえるのはたいへんです。', '背單字很辛苦。',
 ARRAY[]::text[], ARRAY['忘れる'], ARRAY['単語を〜', '名前を〜'],
 'very_high'),

('v-045', 'N4', '忘れる', 'わすれる', '動詞',
 '忘記', 'To forget',
 'パスワードを忘れてしまいました。', 'パスワードをわすれてしまいました。', '把密碼忘了。',
 ARRAY[]::text[], ARRAY['覚える'], ARRAY['〜を忘れる', '〜てしまう'],
 'very_high'),

('v-046', 'N4', '使う', 'つかう', '動詞',
 '使用；用', 'To use',
 'このアプリをよく使います。', 'このアプリをよくつかいます。', '我常用這個應用程式。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を使う', '〜に使う'],
 'very_high'),

('v-047', 'N4', '借りる', 'かりる', '動詞',
 '借（入）；借用', 'To borrow',
 '図書館で本を借りました。', 'としょかんでほんをかりました。', '在圖書館借了書。',
 ARRAY[]::text[], ARRAY['返す', '貸す'], ARRAY['〜を借りる', '〜から借りる'],
 'high'),

('v-048', 'N4', '返す', 'かえす', '動詞',
 '歸還；還', 'To return (something)',
 '本を返すのを忘れないでください。', 'ほんをかえすのをわすれないでください。', '不要忘記還書。',
 ARRAY[]::text[], ARRAY['借りる'], ARRAY['〜を返す', '〜に返す'],
 'high'),

('v-049', 'N4', '手伝う', 'てつだう', '動詞',
 '幫忙；協助', 'To help / to assist',
 '引っ越しを手伝ってもらえますか？', 'ひっこしをてつだってもらえますか？', '可以幫我搬家嗎？',
 ARRAY['助ける'], ARRAY[]::text[], ARRAY['〜を手伝う', '〜てもらえますか'],
 'high'),

('v-050', 'N4', '連絡する', 'れんらくする', '動詞',
 '聯絡；通知', 'To contact / to notify',
 '後で連絡します。', 'あとでれんらくします。', '之後我會聯絡你。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜に連絡する', '〜と連絡をとる'],
 'very_high'),

('v-051', 'N4', '説明する', 'せつめいする', '動詞',
 '說明；解釋', 'To explain',
 'もう一度説明してください。', 'もういちどせつめいしてください。', '請再說明一次。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を説明する', '〜に説明する'],
 'high'),

('v-052', 'N4', '確認する', 'かくにんする', '動詞',
 '確認；確認一下', 'To confirm / to check',
 'メールを確認しましたか？', 'メールをかくにんしましたか？', '你確認郵件了嗎？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を確認する', 'もう一度〜'],
 'very_high'),

('v-053', 'N4', '準備する', 'じゅんびする', '動詞',
 '準備', 'To prepare',
 '旅行の準備をしています。', 'りょこうのじゅんびをしています。', '正在準備旅行。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜の準備', '〜を準備する'],
 'high'),

('v-054', 'N4', '参加する', 'さんかする', '動詞',
 '參加', 'To participate / to join',
 'パーティーに参加しますか？', 'パーティーにさんかしますか？', '你會參加派對嗎？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜に参加する', '〜に参加してください'],
 'high'),

('v-055', 'N4', '紹介する', 'しょうかいする', '動詞',
 '介紹', 'To introduce',
 '友達を紹介してください。', 'ともだちをしょうかいしてください。', '請介紹你的朋友給我。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜を紹介する', '〜に〜を紹介する'],
 'high'),

('v-056', 'N4', '便利', 'べんり', 'ナ形',
 '方便的；便利的', 'Convenient',
 'このアプリはとても便利です。', 'このアプリはとてもべんりです。', '這個應用程式非常方便。',
 ARRAY[]::text[], ARRAY['不便'], ARRAY['〜な道具', '〜な場所'],
 'very_high'),

('v-057', 'N4', '大切', 'たいせつ', 'ナ形',
 '重要的；珍貴的', 'Important / precious',
 '健康はとても大切です。', 'けんこうはとてもたいせつです。', '健康非常重要。',
 ARRAY['重要', '大事'], ARRAY[]::text[], ARRAY['〜な人', '〜にする', '〜なこと'],
 'very_high'),

('v-058', 'N4', '必要', 'ひつよう', 'ナ形',
 '必要的', 'Necessary',
 'ビザが必要ですか？', 'ビザがひつようですか？', '需要簽證嗎？',
 ARRAY[]::text[], ARRAY['不必要'], ARRAY['〜がある', '〜な書類', '〜に応じて'],
 'very_high'),

('v-059', 'N4', '丁寧', 'ていねい', 'ナ形',
 '禮貌的；細心的', 'Polite / careful',
 '丁寧なメールを書きました。', 'ていねいなメールをかきました。', '寫了一封禮貌的郵件。',
 ARRAY[]::text[], ARRAY['失礼'], ARRAY['〜な言葉', '〜に話す'],
 'medium'),

('v-060', 'N4', '複雑', 'ふくざつ', 'ナ形',
 '複雜的', 'Complicated / complex',
 '文法が複雑でわかりません。', 'ぶんぽうがふくざつでわかりません。', '文法很複雜，我不懂。',
 ARRAY[]::text[], ARRAY['簡単'], ARRAY['〜な問題', '〜な気持ち'],
 'high'),

('v-061', 'N4', '機会', 'きかい', '名詞',
 '機會', 'Opportunity / chance',
 'いい機会なので、挑戦してみます。', 'いいきかいなので、ちょうせんしてみます。', '既然是好機會，我要試著挑戰看看。',
 ARRAY['チャンス'], ARRAY[]::text[], ARRAY['〜がある', '〜を生かす', 'いい〜'],
 'high'),

('v-062', 'N4', '理由', 'りゆう', '名詞',
 '理由；原因', 'Reason',
 '理由を教えてください。', 'りゆうをおしえてください。', '請告訴我理由。',
 ARRAY['わけ', '原因'], ARRAY[]::text[], ARRAY['〜を話す', '〜がある', '〜もなく'],
 'high'),

('v-063', 'N4', '予定', 'よてい', '名詞',
 '預定；計畫', 'Plan / schedule',
 '今週末は予定がありますか？', 'こんしゅうまつはよていがありますか？', '這週末有預定行程嗎？',
 ARRAY['計画', 'スケジュール'], ARRAY[]::text[], ARRAY['〜がある', '〜を立てる', '〜通り'],
 'very_high'),

('v-064', 'N4', '経験', 'けいけん', '名詞',
 '經驗；體驗', 'Experience',
 '海外旅行の経験はありますか？', 'かいがいりょこうのけいけんはありますか？', '你有出國旅遊的經驗嗎？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜がある', '〜を積む', '〜を生かす'],
 'high'),

('v-065', 'N4', '気持ち', 'きもち', '名詞',
 '心情；感受', 'Feeling / mood',
 '気持ちをうまく伝えられません。', 'きもちをうまくつたえられません。', '無法好好地表達心情。',
 ARRAY['気分'], ARRAY[]::text[], ARRAY['〜を伝える', '〜がいい', '〜がわかる'],
 'very_high'),

('v-066', 'N4', '意味', 'いみ', '名詞',
 '意思；含義', 'Meaning',
 'この言葉の意味は何ですか？', 'このことばのいみはなんですか？', '這個詞是什麼意思？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜がわかる', '〜を調べる'],
 'very_high'),

('v-067', 'N4', '場合', 'ばあい', '名詞',
 '情況；場合', 'Case / situation',
 '急ぎの場合は電話してください。', 'いそぎのばあいはでんわしてください。', '緊急的情況請打電話。',
 ARRAY['場面'], ARRAY[]::text[], ARRAY['〜によって', '〜は〜する', 'その〜'],
 'high'),

('v-068', 'N4', '関係', 'かんけい', '名詞',
 '關係', 'Relationship / connection',
 '二つの問題は関係があります。', 'ふたつのもんだいはかんけいがあります。', '兩個問題有關聯。',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜がある', '〜ない', '〜を保つ'],
 'high'),

('v-069', 'N4', '方法', 'ほうほう', '名詞',
 '方法；方式', 'Method / way',
 'もっといい方法があります。', 'もっといいほうほうがあります。', '有更好的方法。',
 ARRAY['やり方'], ARRAY[]::text[], ARRAY['〜を探す', '〜を考える', '別の〜'],
 'high'),

('v-070', 'N4', '生活', 'せいかつ', '名詞',
 '生活', 'Life / living',
 '日本での生活に慣れましたか？', 'にほんでのせいかつになれましたか？', '習慣日本的生活了嗎？',
 ARRAY[]::text[], ARRAY[]::text[], ARRAY['〜に慣れる', '〜を送る', '日常〜'],
 'high')

ON CONFLICT (id) DO UPDATE SET
  level            = EXCLUDED.level,
  kanji            = EXCLUDED.kanji,
  reading          = EXCLUDED.reading,
  pos              = EXCLUDED.pos,
  meaning_zh       = EXCLUDED.meaning_zh,
  meaning_en       = EXCLUDED.meaning_en,
  example_ja       = EXCLUDED.example_ja,
  example_reading  = EXCLUDED.example_reading,
  example_zh       = EXCLUDED.example_zh,
  synonyms         = EXCLUDED.synonyms,
  antonyms         = EXCLUDED.antonyms,
  collocations     = EXCLUDED.collocations,
  conversation_freq = EXCLUDED.conversation_freq,
  updated_at       = timezone('utc', now());
